{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bibot.serviceAccountName" . }}
  labels:
    {{- include "bibot.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
    vault.kubernetes.io/role: kubernetes/role/secret-read
  {{- end }}
{{- end }}
